.PHONY: clean pristine

clean:
	$(MAKE) -C functions $@
	$(MAKE) -C intro $@
	$(MAKE) -C pointers $@
	$(MAKE) -C varstat $@
	$(MAKE) -C arrays $@
	$(MAKE) -C strings $@
	$(MAKE) -C structs $@
	$(MAKE) -C io $@
	$(MAKE) -C typedef $@
	$(MAKE) -C pointers2 $@

pristine:
	$(MAKE) -C functions $@
	$(MAKE) -C intro $@
	$(MAKE) -C pointers $@
	$(MAKE) -C varstat $@
	$(MAKE) -C arrays $@
	$(MAKE) -C strings $@
	$(MAKE) -C structs $@
	$(MAKE) -C io $@
	$(MAKE) -C typedef $@
	$(MAKE) -C pointers2 $@
