.PHONY: clean

clean:
	$(MAKE) -C functions $@
	$(MAKE) -C intro $@
	$(MAKE) -C pointers $@
	$(MAKE) -C varstat $@
	$(MAKE) -C arrays $@

pristine:
	$(MAKE) -C functions $@
	$(MAKE) -C intro $@
	$(MAKE) -C pointers $@
	$(MAKE) -C varstat $@
	$(MAKE) -C arrays $@
