#!/usr/bin/python

import sys
import re
import os

#-----------------------------------
# usage
#
def usageexit():
	sys.stderr.write("usage: breakhtml [-d outputdir] source.html\n");
	sys.exit(1)

#-----------------------------------
# globals
#
outdir = "."
infilename = None

#-----------------------------------
# parse the command line
#
i = 1
c = len(sys.argv)
while i < c:
	if sys.argv[i] == "-d":
		i = i + 1
		if i == c: usageexit()
		outdir = sys.argv[i]

	elif infilename == None:
		infilename = sys.argv[i]

	else: usageexit()

	i = i + 1

if infilename == None: usageexit()

infile = file(infilename)
outfile = None

#-----------------------------------
# break up the file
#
for line in infile:
	match = re.search("<!-- BEEJ-GUIDE-OUTPUT-REDIRECT ([^ ]+) -->", line);
	if match != None:
		outfilename = outdir + os.sep + match.group(1)
		if outfile != None: outfile.close()
		outfile = file(outfilename, "w")
	else:
		if outfile != None: outfile.write(line)

#-----------------------------------
# all done
#
if outfile != None: outfile.close()
infile.close()

