BIN=../bin

#all: single multi
all: single

bgc.html: bgc.xml bg.dtd bghtml.xsl
	Xalan -o $@ -v $< bghtml.xsl

bgc.aux: bgc.xml bg.dtd bghtml.xsl
	Xalan -p multipage 1 -o $@ -v $< bghtml.xsl

bgc.tex: bgc.xml bg.dtd bgtex.xsl
	Xalan -o $@ -v $< bgtex.xsl

bgc.pdf: bgc.tex
	pdftex $@
	pdftex $@
	makepdfol < pdfoutline.aux > pdfoutline2.aux
	pdftex $@

.PHONY: single
single: bgc.html

.PHONY: multi
multi: bgc.aux
	rm -rf html
	mkdir html
	chmod 755 html
	$(BIN)/htmlbreak -d html bgc.aux
	#cp *.gif html

.PHONY: clean
clean:
	rm -f *.aux

.PHONY: upload
upload:
	( cd ..; rsync -rv -e ssh * beej.us:~/text/cbook )
