TITLE="Beej's Guide to C Programming"
SUBTITLE=""
AUTHOR='Brian “Beej Jorgensen” Hall'
VERSION_DATE="v0.11.0, Copyright © September 26, 2026"

GUIDE_ID=bgc
BGBSPD_BUILD_DIR?=../../bgbspd

#WEB_IMAGES=$(wildcard img_*.svg)

include $(BGBSPD_BUILD_DIR)/source.make
