TITLE="Beej's Guide to C Programming"
SUBTITLE=""
AUTHOR='Brian “Beej Jorgensen” Hall'
VERSION_DATE="v0.9.23, Copyright © April 1, 2025"

GUIDE_ID=bgc
BGBSPD_BUILD_DIR?=../../bgbspd

#WEB_IMAGES=$(wildcard img_*.svg)

include $(BGBSPD_BUILD_DIR)/source.make
