CC=gcc
CCOPTS=-Wall -Wextra

.PHONY: all clean pristine

all:
	$(MAKE) -C examples $@
	#$(MAKE) -C man $@
	#$(MAKE) -C exercises $@

clean:
	$(MAKE) -C examples $@
	#$(MAKE) -C man $@
	#$(MAKE) -C exercises $@

pristine: clean